### ISSUE TITLE
Multi-line snippet not indenting properly

### ISSUE THREAD

**Issue by ffxsam** [atom/snippets#213]
Snippet indentation is incorrect. I have the following snippet:

``` cson
'.source.js':
  'React method':
    'prefix': 'rm',
    'body': """
    $1 = ($2) => {
      $3
    };
    """
```

I open a .js file and type "rm" then hit tab and fill it in.

**Expected behavior:** [What you expected to happen]

Expected result: (e.g.):

``` js
  testMethod = () => {
    this.doSomething();
  };
```

**Actual behavior:** [What actually happened]

``` js
  testMethod = () => {
     this.doSomething();
   };
```
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

```
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.9.3

Mac OS 10.11.6
```

**Comment by ffxsam** [comment]
Updated post to include more details.

**Comment by xykivo** [comment]
I'm also seeing this issue on 1.10.

**Comment by ffxsam** [comment]
This is still a problem. I now have two snippets that don't indent properly (on Babel JS filetypes).

```
'.source.js':
  'React Method':
    'prefix': 'rmethod',
    'body': """
      $1 = ($2) => {
        $3
      };
    """
  'React PropType':
    'prefix': 'rptype',
    'body': """
      /*
       * $1
       */
       $2: PropTypes.$3
    """
```

The issue seems to be with a `$` argument at the beginning of a line.

**Comment by inwardmovement** [comment]
I have the same problem.

**Comment by inwardmovement** [comment]
this issue has not been solved in one year ? will it be some time so we can use Atom properly ?

**Comment by ffxsam** [comment]
@50Wliu Any updates on this?

**Comment by 50Wliu** [comment]
No.  Contributions are gladly appreciated.

**Comment by mikeerickson** [comment]
@50Wliu oft to complain, but slow to contribute.  Sums up OSS in a nutshell.  I however appreciate your efforts in making snippets available in Atom!

**Comment by ffxsam** [comment]
@mikeerickson Pardon me, but I was filing an issue and following up. Not “complaining.” And some of us are full-time devs working 60-80 hours per week, with no time for OSS contributions.

**Comment by mikeerickson** [comment]
@ffxsam I am a full time developer myself, working 6 days/week, 12-15 hour days... Don't need to battle about working hours.  

Further the complaint was not from you, but rather @inwardmovement "this issue has not been solved in one year? will it be some time so we can use Atom properly ?"  

Atom works properly, just has an issue with expanding a snippet.

**Comment by lee-dohm** [comment]
Let's keep things classy here everyone. We expect everyone to follow the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) in their interactions.

**Comment by ffxsam** [comment]
@mikeerickson I agree, people should keep their issues neutral and not make demands of OSS developers. But we shouldn't make assumptions about people's time availability to make contributions.

**Comment by inwardmovement** [comment]
I agree my message was a bit harsh... please forgive me. I just found it strange that this bug (that totally prevents me from migrating from Notepadd++ to Atom, for example) which seems quite important to me (I agree it is totally personal) was not yet solved. I thought Atom/GitHub community was big and full of passionate and available coders to do "the job" in the minute, but now I realize it is maybe not so simple :) So my bad, this bug will be solved when someone has time to do so and that's it. Maybe I will take a look at it when I have finished other projects, although I don't know anything at Atom coding for now, we never know... Have a good day everyone.

**Comment by ffxsam** [comment]
@inwardmovement Thanks for that :) not to mention, this is not a critical bug either, and there are likely dozens of other things that warrant more attention.

**Comment by 50Wliu** [comment]
Will be fixed by #245.

**Comment by 50Wliu** [comment]
Ah, I see what the problem was.  Indentation was happening after the snippet was inserted.  Since tab stops are removed, it was picking up the space in front of the `=` as extra indentation.  But in #245 indentation happens before the snippet is inserted.

**Comment by vimuel** [comment]
Having the same issue. Thanks for you efforts :)
